inherit_from: .rubocop_todo.yml


AllCops:
  TargetRubyVersion: 3.0.2　
  TargetRailsVersion: 6.1.4.4　
  Exclude: 
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema*.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*" 
    - "app/channels/**/*"
    - "config/**/*"
    - "config.ru"
    - "bin/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"